"use client";

import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { createDiagramLine, createDiagramObject, diagramColors, diagramOrientations, fieldTemplates, lineKinds, objectKinds, type DiagramLineKind, type DiagramObjectKind, type SoccerDiagram } from "../lib/diagram-data";
import { DiagramCanvas } from "./diagram-canvas";

type Props = { initial: SoccerDiagram; drillName: string; onSave: (diagram: SoccerDiagram) => void; onClose: () => void };
type Drag = { id?: string; startX:number; startY:number; original:SoccerDiagram; drawing?:DiagramLineKind };
const objectNames: Record<DiagramObjectKind,string> = {player:"Player",ball:"Ball",cone:"Cone",pole:"Pole",flag:"Flag",goal:"Full goal","mini-goal":"Mini goal",text:"Text"};
const lineNames: Record<DiagramLineKind,string> = {straight:"Straight",dashed:"Dashed",movement:"Movement arrow",passing:"Passing arrow",dribbling:"Dribbling path"};
const fieldNames: Record<SoccerDiagram["field"],string> = {full:"Full Field",half:"Half Field","final-third":"Penalty Area / Final Third",grid:"Blank Field / Grid"};

export function DiagramEditor({initial,drillName,onSave,onClose}:Props) {
  const [diagram,setDiagram]=useState(()=>structuredClone(initial)); const [selected,setSelected]=useState<string|null>(null);
  const [drawTool,setDrawTool]=useState<DiagramLineKind|null>(null); const [past,setPast]=useState<SoccerDiagram[]>([]); const [future,setFuture]=useState<SoccerDiagram[]>([]);
  const [initialJson]=useState(()=>JSON.stringify(initial)); const drag=useRef<Drag|null>(null);
  const dirty=JSON.stringify(diagram)!==initialJson;
  const selectedObject=diagram.objects.find(o=>o.id===selected); const selectedLine=diagram.lines.find(l=>l.id===selected);
  const apply=(change:(current:SoccerDiagram)=>SoccerDiagram)=>{setPast(items=>[...items,structuredClone(diagram)].slice(-50));setFuture([]);setDiagram(change(diagram));};
  const close=()=>{if(!dirty||window.confirm("Discard unsaved diagram changes?"))onClose();};
  useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before)},[dirty]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.key==="Delete"||e.key==="Backspace")&&selected&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPast(items=>[...items,structuredClone(diagram)].slice(-50));setFuture([]);setDiagram(d=>({...d,objects:d.objects.filter(o=>o.id!==selected),lines:d.lines.filter(l=>l.id!==selected)}));setSelected(null)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[diagram,selected]);
  function addObject(kind:DiagramObjectKind){const object=createDiagramObject(kind);apply(d=>({...d,objects:[...d.objects,object]}));setSelected(object.id);setDrawTool(null)}
  function point(e:ReactPointerEvent<SVGElement>){const target=e.currentTarget instanceof SVGSVGElement?e.currentTarget:e.currentTarget.ownerSVGElement!;const rect=target.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))}}
  function pointerDown(e:ReactPointerEvent<SVGElement>,id?:string){const target=e.currentTarget instanceof SVGSVGElement?e.currentTarget:e.currentTarget.ownerSVGElement!;target.setPointerCapture(e.pointerId);const p=point(e);if(drawTool&&!id){const line=createDiagramLine(drawTool,p.x,p.y,p.x,p.y);const original=structuredClone(diagram);setDiagram(d=>({...d,lines:[...d.lines,line]}));setSelected(line.id);drag.current={startX:p.x,startY:p.y,original,drawing:drawTool,id:line.id};return}setSelected(id||null);if(id)drag.current={id,startX:p.x,startY:p.y,original:structuredClone(diagram)}}
  function pointerMove(e:ReactPointerEvent<SVGElement>){if(!drag.current)return;const p=point(e),active=drag.current,dx=p.x-active.startX,dy=p.y-active.startY;if(active.drawing)setDiagram(d=>({...d,lines:d.lines.map(l=>l.id===active.id?{...l,x2:p.x,y2:p.y}:l)}));else setDiagram(d=>({...d,objects:d.objects.map(o=>o.id===active.id?{...o,x:clamp(o.x+dx),y:clamp(o.y+dy)}:o),lines:d.lines.map(l=>l.id===active.id?{...l,x1:clamp(l.x1+dx),y1:clamp(l.y1+dy),x2:clamp(l.x2+dx),y2:clamp(l.y2+dy)}:l)}));active.startX=p.x;active.startY=p.y}
  function pointerUp(){if(!drag.current)return;setPast(items=>[...items,drag.current!.original].slice(-50));setFuture([]);drag.current=null;if(drawTool)setDrawTool(null)}
  function undo(){if(!past.length)return;const previous=past[past.length-1];setFuture(f=>[structuredClone(diagram),...f].slice(0,50));setDiagram(previous);setPast(p=>p.slice(0,-1));setSelected(null)}
  function redo(){if(!future.length)return;const next=future[0];setPast(p=>[...p,structuredClone(diagram)]);setDiagram(next);setFuture(f=>f.slice(1));setSelected(null)}
  function remove(){if(!selected)return;apply(d=>({...d,objects:d.objects.filter(o=>o.id!==selected),lines:d.lines.filter(l=>l.id!==selected)}));setSelected(null)}
  function duplicate(){if(selectedObject){const copy={...selectedObject,id:crypto.randomUUID(),x:clamp(selectedObject.x+.04),y:clamp(selectedObject.y+.04)};apply(d=>({...d,objects:[...d.objects,copy]}));setSelected(copy.id)}else if(selectedLine){const copy={...selectedLine,id:crypto.randomUUID(),x1:clamp(selectedLine.x1+.04),x2:clamp(selectedLine.x2+.04),y1:clamp(selectedLine.y1+.04),y2:clamp(selectedLine.y2+.04)};apply(d=>({...d,lines:[...d.lines,copy]}));setSelected(copy.id)}}
  function updateSelected(values:Record<string,string|number>){apply(d=>({...d,objects:d.objects.map(o=>o.id===selected?{...o,...values}:o),lines:d.lines.map(l=>l.id===selected?{...l,...values}:l)}))}
  function layer(direction:-1|1){if(selectedObject)apply(d=>{const a=[...d.objects],i=a.findIndex(o=>o.id===selected),to=direction<0?0:a.length-1;const [item]=a.splice(i,1);a.splice(to,0,item);return{...d,objects:a}});else if(selectedLine)apply(d=>{const a=[...d.lines],i=a.findIndex(l=>l.id===selected),to=direction<0?0:a.length-1;const [item]=a.splice(i,1);a.splice(to,0,item);return{...d,lines:a}})}
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/95" role="dialog" aria-modal="true" aria-label="Soccer diagram editor"><div className="mx-auto min-h-full max-w-7xl p-3 sm:p-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Diagram builder</p><h2 className="text-xl font-bold sm:text-2xl">{drillName||"Untitled drill"}</h2></div><div className="flex gap-2"><button className="training-secondary" onClick={close}>Cancel</button><button className="training-primary" onClick={()=>onSave(diagram)}>Save &amp; Done</button></div></header>
    <div className="mt-4 grid gap-4 lg:grid-cols-[250px_minmax(0,1fr)_250px]">
      <aside className="training-panel order-2 overflow-hidden p-3 lg:order-1"><h3 className="font-bold">Add to field</h3><p className="mt-1 text-xs text-slate-400">Tap an object, then drag it into place.</p><div className="diagram-tool-scroll mt-3 grid grid-cols-2 gap-2 lg:grid-cols-1">{objectKinds.map(k=><button key={k} className="training-small text-left" onClick={()=>addObject(k)}>+ {objectNames[k]}</button>)}</div><h3 className="mt-5 font-bold">Draw</h3><div className="diagram-tool-scroll mt-3 grid grid-cols-2 gap-2 lg:grid-cols-1">{lineKinds.map(k=><button key={k} aria-pressed={drawTool===k} className={`training-small text-left ${drawTool===k?"ring-2 ring-emerald-400":""}`} onClick={()=>setDrawTool(drawTool===k?null:k)}>↗ {lineNames[k]}</button>)}</div>{drawTool&&<p className="mt-3 rounded-lg bg-emerald-500/10 p-2 text-xs text-emerald-200">Drag on an empty part of the field to draw.</p>}</aside>
      <main className="order-1 min-w-0 lg:order-2"><div className="mb-3 flex flex-wrap items-center gap-2"><button className="training-small" disabled={!past.length} onClick={undo}>↶ Undo</button><button className="training-small" disabled={!future.length} onClick={redo}>↷ Redo</button><span className="text-xs text-slate-400">{dirty?"Unsaved changes":"All changes saved"}</span></div><div className={`mx-auto rounded-xl border-2 border-slate-700 shadow-2xl ${diagram.orientation==="vertical"?"max-w-xl":"max-w-4xl"}`}><DiagramCanvas diagram={diagram} selectedId={selected} interactive onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp}/></div><p className="mt-2 text-center text-xs text-slate-400">Drag objects and lines with a mouse, finger, or stylus. Coordinates scale to every screen.</p></main>
      <aside className="training-panel order-3 p-3"><h3 className="font-bold">Field &amp; selection</h3><label className="training-label mt-3">Template<select className="training-input" value={diagram.field} onChange={e=>apply(d=>({...d,field:e.target.value as SoccerDiagram["field"]}))}>{fieldTemplates.map(f=><option key={f} value={f}>{fieldNames[f]}</option>)}</select></label><label className="training-label mt-3">Orientation<select className="training-input" value={diagram.orientation} onChange={e=>apply(d=>({...d,orientation:e.target.value as SoccerDiagram["orientation"]}))}>{diagramOrientations.map(o=><option key={o}>{o}</option>)}</select></label>
        {(selectedObject||selectedLine)?<div className="mt-5 border-t border-slate-700 pt-4"><p className="font-bold">Selected: {selectedObject?objectNames[selectedObject.kind]:lineNames[selectedLine!.kind]}</p><label className="training-label mt-3">Color<div className="mt-2 flex flex-wrap gap-2">{diagramColors.map(c=><button key={c} onClick={()=>updateSelected({color:c})} aria-label={`Set color ${c}`} className="h-10 w-10 rounded-full border-2" style={{backgroundColor:c,borderColor:(selectedObject||selectedLine)?.color===c?"#34d399":"#64748b"}}/>)}</div></label>{selectedObject&&(selectedObject.kind==="player"||selectedObject.kind==="text")&&<label className="training-label mt-3">Label<input className="training-input" maxLength={selectedObject.kind==="player"?3:30} value={selectedObject.label} onChange={e=>updateSelected({label:e.target.value})}/></label>}{selectedObject?.kind==="player"&&<label className="training-label mt-3">Player shape<select className="training-input" value={selectedObject.playerShape} onChange={e=>updateSelected({playerShape:e.target.value})}><option value="circle">Circle</option><option value="x">X</option><option value="triangle">Triangle</option></select></label>}{selectedObject&&<label className="training-label mt-3">Rotation: {selectedObject.rotation}°<input className="w-full accent-emerald-400" type="range" min="0" max="345" step="15" value={selectedObject.rotation} onChange={e=>updateSelected({rotation:Number(e.target.value)})}/></label>}<div className="mt-4 grid grid-cols-2 gap-2"><button className="training-small" onClick={duplicate}>Duplicate</button><button className="training-small" onClick={()=>layer(1)}>Bring front</button><button className="training-small" onClick={()=>layer(-1)}>Send back</button><button className="training-danger" onClick={remove}>Delete</button></div></div>:<p className="mt-5 rounded-lg bg-slate-800 p-3 text-sm text-slate-400">Select an object or line to edit it.</p>}
      </aside>
    </div>
  </div></div>;
}
function clamp(value:number){return Math.max(.02,Math.min(.98,value))}
