"use client";
import Link from "next/link";
import { useMemo,useSyncExternalStore } from "react";
import { FIXTURE_STORAGE_KEY,GAME_PLAN_STORAGE_KEY,GAMES_DATA_EVENT,ROSTER_STORAGE_KEY,Fixture,GamePlan,Roster,safeCollection } from "../lib/games-data";
import { parseTeams,TEAM_DATA_EVENT,TEAM_STORAGE_KEY } from "../lib/team-data";
import { parsePlayersData,PLAYER_DATA_EVENT,PLAYER_STORAGE_KEY } from "../lib/player-data";
export function subscribeGames(change:()=>void){["storage",GAMES_DATA_EVENT,TEAM_DATA_EVENT,PLAYER_DATA_EVENT].forEach(e=>window.addEventListener(e,change));return()=>["storage",GAMES_DATA_EVENT,TEAM_DATA_EVENT,PLAYER_DATA_EVENT].forEach(e=>window.removeEventListener(e,change));}
export function useGamesData(){const raw=useSyncExternalStore(subscribeGames,()=>[localStorage.getItem(FIXTURE_STORAGE_KEY)||"",localStorage.getItem(ROSTER_STORAGE_KEY)||"",localStorage.getItem(GAME_PLAN_STORAGE_KEY)||"",localStorage.getItem(TEAM_STORAGE_KEY)||"",localStorage.getItem(PLAYER_STORAGE_KEY)||""].join("\u001f"),()=>"\u001f\u001f\u001f\u001f");return useMemo(()=>{const [f,r,g,t,p]=raw.split("\u001f");return{fixtures:safeCollection<Fixture>(f),rosters:safeCollection<Roster>(r),plans:safeCollection<GamePlan>(g),teams:parseTeams(t),players:parsePlayersData(p).players}},[raw]);}
export function GamesHeader({title,eyebrow="Match center",action}:{title:string;eyebrow?:string;action?:React.ReactNode}){return <><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-400">{eyebrow}</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">{title}</h1></div>{action}</div><nav className="mt-6 flex gap-2 overflow-x-auto" aria-label="Games sections"><Link className="training-secondary" href="/games">Overview</Link><Link className="training-secondary" href="/games/schedule">Schedule</Link><Link className="training-secondary" href="/games/rosters">Rosters</Link><Link className="training-secondary" href="/games/game-plans">Game Plans</Link></nav></>}
export function FixtureSummary({fixture,teamName}:{fixture:Fixture;teamName:string}){return <div className="grid gap-3 rounded-xl border border-slate-700 bg-slate-950/60 p-4 sm:grid-cols-2 lg:grid-cols-4"><div><b>{teamName} {fixture.homeAway==="Home"?"vs":"@"} {fixture.opponentName}</b><p className="text-sm text-slate-400">{fixture.competition} · {fixture.stage||"Stage TBD"}</p></div><Info label="Kickoff" value={`${fixture.date||"Date TBD"} · ${fixture.kickoffTime||"Time TBD"}`}/><Info label="Venue" value={fixture.venue||fixture.address||"Venue TBD"}/><Info label="Format" value={`${fixture.fieldFormat} · ${fixture.gameDuration||"—"} min`}/></div>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-200">{value}</p></div>}
