"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useRef, useState, useSyncExternalStore, type ReactNode } from "react";
import { parseTeams, TEAM_DATA_EVENT, TEAM_STORAGE_KEY } from "../lib/team-data";
import { cancellationReasons, duplicateDrill, emptyDrill, emptySession, objectiveAchievements, parseTrainingSessions, saveTrainingSessions, sessionTypes, TRAINING_DATA_EVENT, TRAINING_STORAGE_KEY, type TrainingDrill, type TrainingReport, type TrainingSession } from "../lib/training-data";
import { packDiagram, unpackDiagram } from "../lib/diagram-data";
import { DiagramCanvas } from "./diagram-canvas";
import { DiagramEditor } from "./diagram-editor";
import { TrainingShell } from "./training-shell";

function subscribe(change: () => void) { window.addEventListener("storage", change); window.addEventListener(TRAINING_DATA_EVENT, change); window.addEventListener(TEAM_DATA_EVENT, change); return () => { window.removeEventListener("storage", change); window.removeEventListener(TRAINING_DATA_EVENT, change); window.removeEventListener(TEAM_DATA_EVENT, change); }; }
const reportBlank: Omit<TrainingReport, "completedAt"> = { objectiveAchievement: "Achieved", whatWentWell: "", whatCouldBeBetter: "", nextSteps: "", coachComments: "", followUpNeeded: false, followUpNotes: "" };
type Props = { sessionId?: string };

export function TrainingSessionEditor({ sessionId }: Props) {
  const router = useRouter();
  const raw = useSyncExternalStore(subscribe, () => localStorage.getItem(TRAINING_STORAGE_KEY) ?? "", () => "");
  const teamRaw = useSyncExternalStore(subscribe, () => localStorage.getItem(TEAM_STORAGE_KEY) ?? "", () => "");
  const stored = useMemo(() => parseTrainingSessions(raw), [raw]); const teams = useMemo(() => parseTeams(teamRaw), [teamRaw]);
  const existing = sessionId ? stored.find(s => s.id === sessionId) : undefined;
  const [draft, setDraft] = useState<TrainingSession>(() => existing ? structuredClone(existing) : emptySession());
  const [loadedId, setLoadedId] = useState<string>();
  const [mode, setMode] = useState<"edit"|"report"|"cancel">("edit");
  const [report, setReport] = useState(reportBlank);
  const [editingDiagram, setEditingDiagram] = useState<string|null>(null);
  const [savedFeedback, setSavedFeedback] = useState(false);
  const saveTimer = useRef<ReturnType<typeof setTimeout>|null>(null);
  if (existing && loadedId !== existing.id) { setDraft(structuredClone(existing)); setLoadedId(existing.id); }
  const update = <K extends keyof TrainingSession>(key: K, value: TrainingSession[K]) => setDraft(current => ({ ...current, [key]: value }));
  const updateDrill = <K extends keyof TrainingDrill>(id: string, key: K, value: TrainingDrill[K]) => update("drills", draft.drills.map(d => d.id === id ? {...d, [key]: value} : d));
  const drillMinutes = draft.drills.reduce((sum,d) => sum + (Number(d.duration)||0),0);
  function persist(next = draft) { const saved = {...next, updatedAt: new Date().toISOString()}; saveTrainingSessions([...stored.filter(s=>s.id !== saved.id), saved]); setDraft(saved); setSavedFeedback(true); if(saveTimer.current)clearTimeout(saveTimer.current); saveTimer.current=setTimeout(()=>setSavedFeedback(false),2200); if (!sessionId) router.replace(`/training/${saved.id}`); }
  function move(index: number, direction: -1|1) { const target=index+direction; if(target<0||target>=draft.drills.length)return; const drills=[...draft.drills]; [drills[index],drills[target]]=[drills[target],drills[index]]; update("drills",drills); }
  function submitReport() { persist({...draft,status:"Completed",report:{...report,completedAt:new Date().toISOString()},cancellationReason:null,cancellationNotes:""}); setMode("edit"); }
  function cancelSession() { if (!draft.cancellationReason) return; persist({...draft,status:"Canceled",report:null}); setMode("edit"); }
  if (sessionId && raw && !existing) return <TrainingShell><div className="mx-auto max-w-3xl px-6 py-20 text-center"><h1 className="text-2xl font-bold">Session not found</h1><Link href="/training" className="mt-4 inline-block text-emerald-400">Back to Training</Link></div></TrainingShell>;
  const activeDrill=draft.drills.find(d=>d.id===editingDiagram);
  return <TrainingShell><div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-10">
    {activeDrill&&<DiagramEditor initial={unpackDiagram(activeDrill.diagram)} drillName={activeDrill.name} onClose={()=>setEditingDiagram(null)} onSave={diagram=>{updateDrill(activeDrill.id,"diagram",packDiagram(diagram));setEditingDiagram(null)}}/>}
    <Link href="/training" className="text-sm font-semibold text-slate-400 hover:text-emerald-400">← Training history</Link>
    <div className="mt-6 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-400">{sessionId ? "Training session" : "New session"}</p><h1 className="mt-2 text-3xl font-bold">{draft.mainObjective || "Plan training session"}</h1><p className="mt-2 text-slate-400">Status: <span className="font-semibold text-white">{draft.status}</span></p></div><div className="flex flex-wrap gap-2"><SaveButton saved={savedFeedback} onClick={()=>persist()}/>{sessionId && draft.status==="Planned" && <><button onClick={()=>setMode("report")} className="training-secondary">Complete / Add Report</button><button onClick={()=>setMode("cancel")} className="training-danger">Cancel Session</button></>}</div></div>
    {mode === "report" && <section className="training-panel mt-7 border-emerald-500/40"><div className="flex justify-between"><h2 className="text-xl font-bold">Post-training report</h2><button onClick={()=>setMode("edit")} className="text-slate-400">Close</button></div><p className="mt-1 text-sm text-slate-400">The original plan stays attached to this report.</p><div className="training-form-grid mt-5"><Field label="Objective Achievement"><select className="training-input" value={report.objectiveAchievement} onChange={e=>setReport({...report,objectiveAchievement:e.target.value as TrainingReport["objectiveAchievement"]})}>{objectiveAchievements.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="What Went Well" wide><textarea className="training-input" value={report.whatWentWell} onChange={e=>setReport({...report,whatWentWell:e.target.value})}/></Field><Field label="What Could Be Better" wide><textarea className="training-input" value={report.whatCouldBeBetter} onChange={e=>setReport({...report,whatCouldBeBetter:e.target.value})}/></Field><Field label="Next Steps" wide><textarea className="training-input" value={report.nextSteps} onChange={e=>setReport({...report,nextSteps:e.target.value})}/></Field><Field label="Coach Comments / Observations" wide><textarea className="training-input" value={report.coachComments} onChange={e=>setReport({...report,coachComments:e.target.value})}/></Field><Field label="Follow-up Needed"><select className="training-input" value={report.followUpNeeded?"yes":"no"} onChange={e=>setReport({...report,followUpNeeded:e.target.value==="yes"})}><option value="no">No</option><option value="yes">Yes</option></select></Field>{report.followUpNeeded&&<Field label="Follow-up Timing / Notes" wide><textarea className="training-input" value={report.followUpNotes} onChange={e=>setReport({...report,followUpNotes:e.target.value})}/></Field>}</div><button onClick={submitReport} className="training-primary mt-5">Complete Session</button></section>}
    {mode === "cancel" && <section className="training-panel mt-7 border-rose-500/40"><h2 className="text-xl font-bold">Cancel session</h2><div className="training-form-grid mt-5"><Field label="Cancellation Reason"><select className="training-input" value={draft.cancellationReason??""} onChange={e=>update("cancellationReason",e.target.value as TrainingSession["cancellationReason"])}><option value="">Select reason</option>{cancellationReasons.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Cancellation Notes" wide><textarea className="training-input" value={draft.cancellationNotes} onChange={e=>update("cancellationNotes",e.target.value)}/></Field></div><div className="mt-5 flex gap-2"><button onClick={cancelSession} className="training-danger">Confirm Cancellation</button><button onClick={()=>setMode("edit")} className="training-secondary">Keep Planned</button></div></section>}
    {draft.report && <section className="training-panel mt-7 border-emerald-500/30"><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Completed report</p><h2 className="mt-2 text-xl font-bold">{draft.report.objectiveAchievement}</h2><div className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><ReportItem label="What went well" value={draft.report.whatWentWell}/><ReportItem label="What could be better" value={draft.report.whatCouldBeBetter}/><ReportItem label="Next steps" value={draft.report.nextSteps}/><ReportItem label="Coach observations" value={draft.report.coachComments}/><ReportItem label="Follow-up" value={draft.report.followUpNeeded ? draft.report.followUpNotes || "Needed" : "Not needed"}/></div></section>}
    {draft.status === "Canceled" && <section className="training-panel mt-7 border-rose-500/30"><p className="text-xs font-bold uppercase tracking-widest text-rose-300">Canceled</p><p className="mt-2 font-semibold">{draft.cancellationReason}</p>{draft.cancellationNotes&&<p className="mt-2 text-sm text-slate-300">{draft.cancellationNotes}</p>}</section>}
    <section className="training-panel mt-7"><h2 className="text-xl font-bold">Session details</h2><div className="training-form-grid mt-5">
      <Field label="Team"><select required className="training-input" value={draft.teamId} onChange={e=>update("teamId",e.target.value)}><option value="">Select team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><DateField value={draft.date} onChange={value=>update("date",value)}/><Field label="Start Time"><input type="time" className="training-input" value={draft.startTime} onChange={e=>update("startTime",e.target.value)}/></Field><NumberField label="Number of Players" value={draft.playerCount} onChange={v=>update("playerCount",v)}/><NumberField label="Total Duration / Volume (min)" value={draft.plannedDuration} onChange={v=>update("plannedDuration",v)}/><Field label="Session Type"><select className="training-input" value={draft.sessionType} onChange={e=>update("sessionType",e.target.value as TrainingSession["sessionType"])}>{sessionTypes.map(v=><option key={v}>{v}</option>)}</select></Field><Text label="Period / Phase" value={draft.period} change={v=>update("period",v)}/><Text label="Weather" value={draft.weather} change={v=>update("weather",v)}/><Text label="Temperature" value={draft.temperature} change={v=>update("temperature",v)}/><Text label="Main Objective" value={draft.mainObjective} change={v=>update("mainObjective",v)} wide/><Text label="Main Principles" value={draft.mainPrinciples} change={v=>update("mainPrinciples",v)} wide/><Area label="Materials / Equipment" value={draft.equipment} change={v=>update("equipment",v)}/><Area label="General Objectives" value={draft.generalObjectives} change={v=>update("generalObjectives",v)}/><Area label="Specific Objectives" value={draft.specificObjectives} change={v=>update("specificObjectives",v)}/><Area label="General Notes" value={draft.notes} change={v=>update("notes",v)}/>
    </div></section>
    <section className="mt-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold">Drills / Exercises</h2><p className="mt-1 text-sm text-slate-400">Drills: {drillMinutes} min · Plan: {draft.plannedDuration} min</p></div><button onClick={()=>update("drills",[...draft.drills,emptyDrill()])} className="training-primary">+ Add Drill</button></div>{drillMinutes !== draft.plannedDuration && <p className="mt-4 rounded-xl border border-amber-500/25 bg-amber-500/10 p-3 text-sm text-amber-200">Drill time differs from planned session duration by {Math.abs(drillMinutes-draft.plannedDuration)} minutes. You can still save.</p>}
      <div className="mt-4 space-y-4">{draft.drills.map((d,index)=><article key={d.id} className="training-panel"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h3 className="font-bold text-emerald-300">Drill {index+1}: {d.name||"Untitled"}</h3><div className="flex flex-wrap gap-2"><button onClick={()=>move(index,-1)} disabled={index===0} className="training-small">↑ Up</button><button onClick={()=>move(index,1)} disabled={index===draft.drills.length-1} className="training-small">↓ Down</button><button onClick={()=>update("drills",[...draft.drills.slice(0,index+1),duplicateDrill(d),...draft.drills.slice(index+1)])} className="training-small">Duplicate</button><button onClick={()=>update("drills",draft.drills.filter(x=>x.id!==d.id))} className="training-small text-rose-300">Delete</button></div></div><div className="training-form-grid mt-5"><Text label="Drill Name" value={d.name} change={v=>updateDrill(d.id,"name",v)} wide/><NumberField label="Duration (min)" value={d.duration} onChange={v=>updateDrill(d.id,"duration",v)}/><NumberField label="Number of Players" value={d.playerCount} onChange={v=>updateDrill(d.id,"playerCount",v)}/><Text label="Area / Space" value={d.area} change={v=>updateDrill(d.id,"area",v)}/><Area label="Specific Objective(s)" value={d.objectives} change={v=>updateDrill(d.id,"objectives",v)}/><Area label="Description / Organization" value={d.description} change={v=>updateDrill(d.id,"description",v)}/><Area label="Coaching Points" value={d.coachingPoints} change={v=>updateDrill(d.id,"coachingPoints",v)}/><Area label="Progressions / Variations" value={d.progressions} change={v=>updateDrill(d.id,"progressions",v)}/><Area label="Notes" value={d.notes} change={v=>updateDrill(d.id,"notes",v)}/></div>{d.diagram?<button type="button" onClick={()=>setEditingDiagram(d.id)} className="mt-4 block w-full overflow-hidden rounded-xl border border-slate-700 bg-slate-950 p-2 text-left hover:border-emerald-500" aria-label={`Edit diagram for ${d.name||"drill"}`}><div className="mx-auto max-w-md"><DiagramCanvas diagram={unpackDiagram(d.diagram)}/></div><span className="mt-2 block text-center text-sm font-bold text-emerald-300">Edit Diagram</span></button>:<button type="button" onClick={()=>setEditingDiagram(d.id)} className="mt-4 min-h-16 w-full rounded-xl border border-dashed border-emerald-500/50 bg-emerald-500/5 text-sm font-bold text-emerald-300 hover:bg-emerald-500/10">+ Create Diagram</button>}</article>)}</div>
    </section><div className="sticky bottom-3 mt-8 rounded-2xl border border-slate-700 bg-slate-900/95 p-3 shadow-2xl backdrop-blur"><SaveButton saved={savedFeedback} onClick={()=>persist()} wide/></div>
  </div></TrainingShell>;
}
function Field({label,wide,children}:{label:string;wide?:boolean;children:ReactNode}) { return <label className={`block ${wide?"sm:col-span-2":""}`}><span className="training-label">{label}</span>{children}</label>; }
function DateField({value,onChange}:{value:string;onChange:(value:string)=>void}) {
  const inputRef = useRef<HTMLInputElement>(null);
  const openCalendar = () => {
    const input = inputRef.current;
    if (!input) return;
    input.focus();
    if (typeof input.showPicker === "function") input.showPicker();
  };
  return <div><label htmlFor="training-session-date" className="training-label">Date</label><div className="flex gap-2"><input ref={inputRef} id="training-session-date" type="date" className="training-input min-w-0 [color-scheme:dark]" value={value} onChange={e=>onChange(e.target.value)}/><button type="button" onClick={openCalendar} aria-label="Choose training session date from calendar" title="Choose date" className="training-secondary flex min-h-12 min-w-12 items-center justify-center px-3" ><svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5 fill-none stroke-current" strokeWidth="2"><path d="M7 2v3M17 2v3M3.5 9h17M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/></svg></button></div></div>;
}
function Text({label,value,change,wide}:{label:string;value:string;change:(v:string)=>void;wide?:boolean}) { return <Field label={label} wide={wide}><input className="training-input" value={value} onChange={e=>change(e.target.value)}/></Field>; }
function Area({label,value,change}:{label:string;value:string;change:(v:string)=>void}) { return <Field label={label} wide><textarea className="training-input min-h-24" value={value} onChange={e=>change(e.target.value)}/></Field>; }
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}) { return <Field label={label}><input type="number" min="0" className="training-input" value={value||""} onChange={e=>onChange(Number(e.target.value))}/></Field>; }
function ReportItem({label,value}:{label:string;value:string}) { return <div><p className="font-semibold text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap text-slate-200">{value || "—"}</p></div>; }
function SaveButton({saved,onClick,wide}:{saved:boolean;onClick:()=>void;wide?:boolean}) { return <button onClick={onClick} className={`training-primary ${wide?"w-full sm:w-auto":""}`} aria-live="polite">{saved?"✓ Saved":"Save Session"}</button>; }
