"use client";

import Link from "next/link";
import { useMemo, useState, useSyncExternalStore } from "react";
import { DiagramCanvas } from "../../../components/diagram-canvas";
import { TrainingShell } from "../../../components/training-shell";
import { unpackDiagram } from "../../../lib/diagram-data";
import { DRILL_LIBRARY_EVENT, DRILL_LIBRARY_STORAGE_KEY, drillAgeGroups, drillCategories, duplicateLibraryDrill, parseLibraryDrills, saveLibraryDrills } from "../../../lib/drill-library-data";
import { sessionTypes } from "../../../lib/training-data";
const subscribe = (change: () => void) => { window.addEventListener("storage", change); window.addEventListener(DRILL_LIBRARY_EVENT, change); return () => { window.removeEventListener("storage", change); window.removeEventListener(DRILL_LIBRARY_EVENT, change); }; };
export default function DrillLibraryPage() {
  const raw = useSyncExternalStore(subscribe, () => localStorage.getItem(DRILL_LIBRARY_STORAGE_KEY) ?? "", () => ""); const drills = useMemo(() => parseLibraryDrills(raw).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)), [raw]);
  const [search,setSearch]=useState(""); const [category,setCategory]=useState(""); const [type,setType]=useState(""); const [age,setAge]=useState("");
  const visible=drills.filter(d => (!category||d.category===category)&&(!type||d.sessionType===type)&&(!age||d.ageGroups.includes(age))&&(!search||`${d.name} ${d.objectives} ${d.category} ${d.tags.join(" ")} ${d.description}`.toLowerCase().includes(search.toLowerCase())));
  const copy=(id:string)=>{const source=drills.find(d=>d.id===id);if(source)saveLibraryDrills([...drills,duplicateLibraryDrill(source)])};
  const remove=(id:string)=>{if(confirm("Delete this library drill? Session snapshots created from it will remain unchanged."))saveLibraryDrills(drills.filter(d=>d.id!==id))};
  return <TrainingShell><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-400">Training</p><h1 className="mt-2 text-3xl font-bold">Personal drill library</h1><p className="mt-2 text-slate-400">Build reusable exercises, then add independent snapshots to sessions.</p></div><Link href="/training/drills/new" className="training-primary">+ New Drill</Link></header>
  <div className="mt-7 grid gap-3 rounded-2xl border border-slate-800 bg-slate-900 p-4 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Search drills" className="training-input" placeholder="Search drills, tags, objectives…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter category" className="training-input" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{drillCategories.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Filter training type" className="training-input" value={type} onChange={e=>setType(e.target.value)}><option value="">All training types</option>{sessionTypes.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Filter age group" className="training-input" value={age} onChange={e=>setAge(e.target.value)}><option value="">All age groups</option>{drillAgeGroups.map(v=><option key={v}>{v}</option>)}</select></div>
  <p className="mt-5 text-sm text-slate-400">{visible.length} of {drills.length} drills</p><div className="mt-3 space-y-3">{visible.map(d=><article key={d.id} className="grid gap-4 rounded-2xl border border-slate-800 bg-slate-900 p-4 sm:grid-cols-[180px_minmax(0,1fr)_auto] sm:items-center">{d.diagram?<div className="overflow-hidden rounded-xl"><DiagramCanvas diagram={unpackDiagram(d.diagram)}/></div>:<div className="flex min-h-28 items-center justify-center rounded-xl border border-dashed border-slate-700 text-xs text-slate-500">No diagram</div>}<Link href={`/training/drills/${d.id}`} className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-bold text-emerald-300">{d.category}</span><span className="px-1 py-1 text-xs text-slate-400">{d.duration||"—"} min · {d.playerCount||"—"} players</span></div><h2 className="mt-2 text-lg font-bold">{d.name}</h2><p className="mt-1 line-clamp-2 text-sm text-slate-300">{d.objectives||d.description||"No objective added"}</p><p className="mt-2 text-xs text-slate-500">{d.ageGroups.join(" · ")||"All ages"}{d.tags.length?` · ${d.tags.join(", ")}`:""}</p></Link><div className="flex gap-2 sm:flex-col"><Link href={`/training/drills/${d.id}`} className="training-secondary">Open / Edit</Link><button onClick={()=>copy(d.id)} className="training-secondary">Duplicate</button><button onClick={()=>remove(d.id)} className="training-danger">Delete</button></div></article>)}{!visible.length&&<div className="rounded-2xl border border-dashed border-slate-700 p-12 text-center text-slate-400">{drills.length?"No drills match these filters.":"Your drill library is empty. Create your first reusable exercise."}</div>}</div></div></TrainingShell>;
}
