"use client";

import Link from "next/link";
import { useMemo, useState, useSyncExternalStore } from "react";
import { DiagramCanvas } from "../../../components/diagram-canvas";
import { TrainingShell } from "../../../components/training-shell";
import { unpackDiagram } from "../../../lib/diagram-data";
import { DRILL_LIBRARY_EVENT, DRILL_LIBRARY_STORAGE_KEY, drillAgeGroups, drillCategories, duplicateLibraryDrill, libraryAreas, parseLibraryDrills, saveLibraryDrills, type LibraryArea } from "../../../lib/drill-library-data";
import { parseTeams, TEAM_DATA_EVENT, TEAM_STORAGE_KEY } from "../../../lib/team-data";
import { sessionTypes } from "../../../lib/training-data";

const areaDetails: Record<LibraryArea, { label: string; short: string }> = {
  personal: { label: "Personal Library", short: "Your private working collection" },
  academy: { label: "Academy / Teams", short: "Club and team coaching content" },
  goalkeeping: { label: "Goalkeeping", short: "Specialist goalkeeper work" },
  performance: { label: "Performance", short: "Physical and athletic development" },
  "mini-kickers": { label: "Mini Kickers / PGS", short: "Story-led young-player activities" },
};
const subscribe = (change: () => void) => { window.addEventListener("storage", change); window.addEventListener(DRILL_LIBRARY_EVENT, change); window.addEventListener(TEAM_DATA_EVENT, change); return () => { window.removeEventListener("storage", change); window.removeEventListener(DRILL_LIBRARY_EVENT, change); window.removeEventListener(TEAM_DATA_EVENT, change); }; };

export default function DrillLibraryPage() {
  const raw = useSyncExternalStore(subscribe, () => localStorage.getItem(DRILL_LIBRARY_STORAGE_KEY) ?? "", () => "");
  const teamRaw = useSyncExternalStore(subscribe, () => localStorage.getItem(TEAM_STORAGE_KEY) ?? "", () => "");
  const drills = useMemo(() => parseLibraryDrills(raw).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)), [raw]);
  const teams = useMemo(() => parseTeams(teamRaw), [teamRaw]);
  const [activeArea,setActiveArea]=useState<LibraryArea>("personal"); const [view,setView]=useState<"full"|"compact">("full");
  const [search,setSearch]=useState(""); const [category,setCategory]=useState(""); const [type,setType]=useState(""); const [age,setAge]=useState(""); const [team,setTeam]=useState("");
  const areaDrills=drills.filter(d=>d.libraryArea===activeArea);
  const visible=areaDrills.filter(d => (!category||d.category===category)&&(!type||d.sessionType===type)&&(!age||d.ageGroups.includes(age))&&(!team||d.teamIds.includes(team))&&(!search||`${d.name} ${d.objectives} ${d.category} ${d.tags.join(" ")} ${d.description} ${d.specialization} ${d.miniKickersTheme?.name??""}`.toLowerCase().includes(search.toLowerCase())));
  const copy=(id:string)=>{const source=drills.find(d=>d.id===id);if(source)saveLibraryDrills([...drills,duplicateLibraryDrill(source)])};
  const remove=(id:string)=>{if(confirm("Delete this library drill? Session snapshots created from it will remain unchanged."))saveLibraryDrills(drills.filter(d=>d.id!==id))};
  const teamNames=(ids:string[])=>ids.map(id=>teams.find(t=>t.id===id)?.name).filter(Boolean).join(", ");
  return <TrainingShell><div className="mx-auto max-w-7xl px-4 py-7 sm:px-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-400">Training ecosystem</p><h1 className="mt-1 text-3xl font-bold">Training Library</h1><p className="mt-2 text-slate-400">One reusable exercise architecture, organized for every coaching department.</p></div><div className="flex flex-wrap gap-2"><div className="flex rounded-xl border border-slate-700 bg-slate-900 p-1" aria-label="Library view"><button className={`rounded-lg px-3 py-2 text-sm font-semibold ${view==="full"?"bg-slate-700 text-white":"text-slate-400"}`} onClick={()=>setView("full")}>Full View</button><button className={`rounded-lg px-3 py-2 text-sm font-semibold ${view==="compact"?"bg-slate-700 text-white":"text-slate-400"}`} onClick={()=>setView("compact")}>Compact View</button></div><Link href={`/training/drills/new?area=${activeArea}`} className="training-primary">+ New Exercise</Link></div></header>
    <nav className="mt-6 grid gap-2 sm:grid-cols-2 lg:grid-cols-5" aria-label="Training library areas">{libraryAreas.map(area=><button key={area} onClick={()=>{setActiveArea(area);setTeam("")}} className={`min-h-20 rounded-xl border p-3 text-left ${activeArea===area?"border-emerald-500 bg-emerald-500/10":"border-slate-800 bg-slate-900 hover:border-slate-600"}`}><span className={`block text-sm font-bold ${activeArea===area?"text-emerald-300":"text-white"}`}>{areaDetails[area].label}</span><span className="mt-1 block text-xs text-slate-400">{drills.filter(d=>d.libraryArea===area).length} exercises · {areaDetails[area].short}</span></button>)}</nav>
    <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between"><div><h2 className="text-xl font-bold">{areaDetails[activeArea].label}</h2><p className="text-sm text-slate-400">{areaDetails[activeArea].short}</p></div><p className="text-sm text-slate-400">{visible.length} of {areaDrills.length} shown</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input aria-label="Search exercises" className="training-input" placeholder="Search content, tags, focus…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter category" className="training-input" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{drillCategories.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Filter training type" className="training-input" value={type} onChange={e=>setType(e.target.value)}><option value="">All training types</option>{sessionTypes.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Filter age group" className="training-input" value={age} onChange={e=>setAge(e.target.value)}><option value="">All age groups</option>{drillAgeGroups.map(v=><option key={v}>{v}</option>)}</select>{activeArea==="academy"?<select aria-label="Filter team" className="training-input" value={team} onChange={e=>setTeam(e.target.value)}><option value="">All academy / teams</option>{teams.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select>:<div className="hidden lg:block"/>}</div></section>
    <div className={`${view==="compact"?"mt-4 grid gap-3 md:grid-cols-2":"mt-4 space-y-3"}`}>{visible.map(d=><article key={d.id} className={`${view==="full"?"grid gap-4 sm:grid-cols-[180px_minmax(0,1fr)_auto]":"flex flex-col"} rounded-2xl border border-slate-800 bg-slate-900 p-4`}>
      {view==="full"&&(d.diagram?<div className="self-center overflow-hidden rounded-xl"><DiagramCanvas diagram={unpackDiagram(d.diagram)}/></div>:<div className="flex min-h-28 items-center justify-center rounded-xl border border-dashed border-slate-700 text-xs text-slate-500">No diagram</div>)}
      <Link href={`/training/drills/${d.id}`} className="min-w-0 self-center"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-bold text-emerald-300">{d.specialization||d.category}</span><span className="px-1 py-1 text-xs text-slate-400">{d.duration||"—"} min · {d.playerCount||"—"} players</span></div><h3 className="mt-2 text-lg font-bold">{d.name}</h3><p className={`${view==="compact"?"line-clamp-1":"line-clamp-2"} mt-1 text-sm text-slate-300`}>{d.objectives||d.description||"No objective added"}</p><p className="mt-2 text-xs text-slate-500">{d.ageGroups.join(" · ")||"All ages"}{d.teamIds.length?` · ${teamNames(d.teamIds)}`:""}{d.miniKickersTheme?.name?` · Theme: ${d.miniKickersTheme.name}`:""}{d.tags.length?` · ${d.tags.join(", ")}`:""}</p>{view==="full"&&<div className="mt-3 grid gap-2 text-xs text-slate-400 sm:grid-cols-2"><p><b className="text-slate-300">Organization:</b> {d.description||"—"}</p><p><b className="text-slate-300">Coaching points:</b> {d.coachingPoints||"—"}</p></div>}</Link>
      <div className={`flex gap-2 ${view==="full"?"sm:flex-col sm:self-center":"mt-4 flex-wrap"}`}><Link href={`/training/drills/${d.id}`} className="training-secondary">Open / Edit</Link><button onClick={()=>copy(d.id)} className="training-secondary">Duplicate</button><button onClick={()=>remove(d.id)} className="training-danger">Delete</button></div>
    </article>)}{!visible.length&&<div className="rounded-2xl border border-dashed border-slate-700 p-12 text-center text-slate-400">{areaDrills.length?"No exercises match these filters.":<>No content in this area yet. <Link href={`/training/drills/new?area=${activeArea}`} className="font-semibold text-emerald-300">Create the first exercise.</Link></>}</div>}</div>
  </div></TrainingShell>;
}
