"use client";

import Link from "next/link";
import { useMemo, useState, useSyncExternalStore } from "react";
import { TrainingShell } from "../../components/training-shell";
import { parseTeams, TEAM_DATA_EVENT, TEAM_STORAGE_KEY } from "../../lib/team-data";
import { duplicateSession, parseTrainingSessions, saveTrainingSessions, sessionStatuses, sessionTypes, TRAINING_DATA_EVENT, TRAINING_STORAGE_KEY } from "../../lib/training-data";

function subscribe(change: () => void) { window.addEventListener("storage", change); window.addEventListener(TRAINING_DATA_EVENT, change); window.addEventListener(TEAM_DATA_EVENT, change); return () => { window.removeEventListener("storage", change); window.removeEventListener(TRAINING_DATA_EVENT, change); window.removeEventListener(TEAM_DATA_EVENT, change); }; }
const badge: Record<string, string> = { Planned: "bg-sky-500/15 text-sky-300", Completed: "bg-emerald-500/15 text-emerald-300", Canceled: "bg-rose-500/15 text-rose-300" };

export default function TrainingPage() {
  const trainingRaw = useSyncExternalStore(subscribe, () => localStorage.getItem(TRAINING_STORAGE_KEY) ?? "", () => "");
  const teamRaw = useSyncExternalStore(subscribe, () => localStorage.getItem(TEAM_STORAGE_KEY) ?? "", () => "");
  const sessions = useMemo(() => parseTrainingSessions(trainingRaw).sort((a,b) => b.date.localeCompare(a.date)), [trainingRaw]);
  const teams = useMemo(() => parseTeams(teamRaw), [teamRaw]); const teamName = (id: string) => teams.find(t => t.id === id)?.name ?? "Unassigned team";
  const [team, setTeam] = useState(""); const [status, setStatus] = useState(""); const [type, setType] = useState(""); const [search, setSearch] = useState("");
  const visible = sessions.filter(s => (!team || s.teamId === team) && (!status || s.status === status) && (!type || s.sessionType === type) && (!search || `${s.mainObjective} ${s.mainPrinciples} ${teamName(s.teamId)} ${s.date}`.toLowerCase().includes(search.toLowerCase())));
  const today = new Date().toISOString().slice(0,10); const upcoming = sessions.filter(s => s.status === "Planned" && s.date >= today).sort((a,b) => a.date.localeCompare(b.date));
  function copy(id: string) { const source = sessions.find(s => s.id === id); if (source) saveTrainingSessions([...sessions, duplicateSession(source)]); }
  function remove(id: string) { if (window.confirm("Delete this training session? This cannot be undone.")) saveTrainingSessions(sessions.filter(s => s.id !== id)); }
  return <TrainingShell><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-10">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-400">Training</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Training center</h1><p className="mt-2 text-slate-400">Plan, run, review, and reuse every session.</p></div><div className="flex flex-wrap gap-2"><Link href="/training/drills" className="training-secondary">Drill Library</Link><Link href="/training/new" className="min-h-12 rounded-xl bg-emerald-500 px-5 py-3 text-center font-bold text-slate-950 hover:bg-emerald-400">+ New Training Session</Link></div></div>
    <section className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Scheduled", sessions.filter(s=>s.status==="Planned").length],["Completed",sessions.filter(s=>s.status==="Completed").length],["Canceled",sessions.filter(s=>s.status==="Canceled").length],["Next session",upcoming[0]?.date || "None"]].map(([label,value])=><div key={label} className="rounded-2xl border border-slate-800 bg-slate-900 p-4 sm:p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-xl font-bold sm:text-2xl">{value}</p></div>)}</section>
    {upcoming.length > 0 && <section className="mt-8 rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Up next</p><div className="mt-2 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">{upcoming[0].mainObjective || "Untitled session"}</h2><p className="mt-1 text-sm text-slate-300">{upcoming[0].date} at {upcoming[0].startTime || "time TBD"} · {teamName(upcoming[0].teamId)}</p></div><Link href={`/training/${upcoming[0].id}`} className="rounded-xl border border-emerald-500/40 px-4 py-3 text-center font-semibold text-emerald-300">Open session</Link></div></section>}
    <section className="mt-10"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-400">History / Log</p><h2 className="mt-1 text-2xl font-bold">All sessions</h2></div>
      <div className="mt-5 grid gap-3 rounded-2xl border border-slate-800 bg-slate-900 p-4 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Search sessions" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search focus, principle, date…" className="training-input"/><select aria-label="Filter by team" value={team} onChange={e=>setTeam(e.target.value)} className="training-input"><option value="">All teams</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)} className="training-input"><option value="">All statuses</option>{sessionStatuses.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Filter by session type" value={type} onChange={e=>setType(e.target.value)} className="training-input"><option value="">All session types</option>{sessionTypes.map(v=><option key={v}>{v}</option>)}</select></div>
      <div className="mt-4 space-y-3">{visible.length ? visible.map(s=><article key={s.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><Link href={`/training/${s.id}`} className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${badge[s.status]}`}>{s.status}</span>{s.report && <span className="text-xs text-slate-400">{s.report.objectiveAchievement}</span>}</div><h3 className="mt-3 truncate text-lg font-bold">{s.mainObjective || "Untitled session"}</h3><p className="mt-1 text-sm text-slate-400">{s.date || "No date"} · {teamName(s.teamId)} · {s.sessionType}</p>{s.mainPrinciples && <p className="mt-2 text-sm text-slate-300">Principles: {s.mainPrinciples}</p>}</Link><div className="flex gap-2"><button onClick={()=>copy(s.id)} className="training-secondary">Duplicate</button><button onClick={()=>remove(s.id)} className="training-danger">Delete</button></div></div></article>) : <div className="rounded-2xl border border-dashed border-slate-700 p-10 text-center text-slate-400">No training sessions match these filters.</div>}</div>
    </section>
  </div></TrainingShell>;
}
